后台大致完成
报错：
NoUniqueBeanDefinitionException: No qualifying bean of type
[javax.persistence.EntityManager] is defined: expected single matching
bean but found 2:
org.springframework.orm.jpa.SharedEntityManagerCreator#0,org.springframework.orm.jpa.SharedEntityManagerCreator#1
错误出在com.wrw.newmanagementsystem.common.dao.CustomBaseSqlDaoImpl类的private
EntityManager em;
解决：
@PersistenceContext
原因未知有空再看看，还有查报错还是上Google，百度就是来搞笑的！！